server:
  port: 8080

spring:
  application:
    name: xiaoyu-yinran-server
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 60MB
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  jwt-expire-hours: 168

springdoc:
  swagger-ui:
    path: /swagger-ui.html
knife4j:
  enable: true
